name: Publish Asset and Create API

on:
  push:
    branches:
      - main

jobs:
  publish_and_create_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Login to Anypoint Platform
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
        run: |
          response=$(curl -s -X POST "https://anypoint.mulesoft.com/accounts/login" \
            -H "Content-Type: application/json" \
            -d '{"username":"'${ANYPOINT_USERNAME}'","password":"'${ANYPOINT_PASSWORD}'"}')
          token=$(echo $response | jq -r '.access_token')
          echo "Anypoint Platform login successful"

      - name: Publish Asset to Exchange
        env:
          ANYPOINT_TOKEN: ${{ token }}
        run: |
          curl -X POST -H "Authorization: Bearer ${ANYPOINT_TOKEN}" \
            -F "file=@cicddemo.raml \
            https://anypoint.mulesoft.com/exchange/api/v2/assets/publish
          echo "Asset published to Exchange successfully"

      - name: Create API in API Manager
        env:
          ANYPOINT_TOKEN: ${{ secrets.ANYPOINT_TOKEN }}
          ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_ORG_ID }}
          API_NAME: "my-api"
          API_DEFINITION: |
            {
              "swagger": "2.0",
              "info": {
                "title": "My API",
                "version": "1.0.0"
              },
              "paths": {
                "/hello": {
                  "get": {
                    "responses": {
                      "200": {
                        "description": "Returns a greeting"
                      }
                    },
                    "x-mule-fc": {
                      "name": "hello",
                      "configurations": [
                        {
                          "environment": "Sandbox",
                          "flowName": "hello"
                        }
                      ]
                    }
                  }
                }
              }
            }
        run: |
          response=$(curl -s -X POST "https://anypoint.mulesoft.com/apimanager/api/v1/organizations/${ANYPOINT_ORG_ID}/environments/Sandbox/apis" \
            -H "Authorization: Bearer ${ANYPOINT_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "'${API_NAME}'",
              "spec": '${API_DEFINITION}'
            }')
          api_id=$(echo $response | jq -r '.id')
          echo "API created in API Manager with ID ${api_id}"

      - name: Output API ID
        run: |
          echo "::set-output name=api_id::${api_id}"
