name: Publish Asset and Create API

on:
  push:
    branches:
      - main

jobs:
  publish_and_create_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq

      - name: Login to Anypoint Platform
        env:
          ANYPOINT_USERNAME: ${{ secrets.ANYPOINT_USERNAME }}
          ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
        run: |
          response=$(curl -s -X POST "https://anypoint.mulesoft.com/accounts/login" \
            -H "Content-Type: application/json" \
            -d '{"username":"'${ANYPOINT_USERNAME}'","password":"'${ANYPOINT_PASSWORD}'"}')
          token=$(echo $response | jq -r '.access_token')
          echo "Anypoint Platform login successful"

      - name: Publish Asset to Exchange
        env:
          ANYPOINT_TOKEN: ${{ secrets.ANYPOINT_TOKEN }}
        run: |          
          curl --location 'https://anypoint.mulesoft.com/exchange/api/v1/assets' \
             --header 'Authorization: Bearer 2d8edace-33b6-453f-ab02-8762ac14f0cc' \
             --form 'organizationId="8ccbc578-b790-45f9-9859-bca06c81adcd"' \
             --form 'groupId="8ccbc578-b790-45f9-9859-bca06c81adcd"' \
             --form 'assetId="mycicddemoapiaprilapril"' \
             --form 'version="1.0.0"' \
             --form 'name="my cicd demo app"' \
             --form 'classifier="raml"' \
             --form 'apiVersion="v1"' \
             --form "asset=@./calculator.raml"
          echo "Asset published to Exchange successfully"

      - name: Create API in API Manager
        env:
          ANYPOINT_TOKEN: ${{ secrets.ANYPOINT_TOKEN }}
          ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_ORG_ID }}

        run: |
          response=$(curl -s -X POST "https://anypoint.mulesoft.com/apimanager/api/v1/organizations/8ccbc578-b790-45f9-9859-bca06c81adcd/environments/7001f5f5-7165-4e3c-833b-f63282df9523/apis" \
            -H "Authorization: Bearer ${ANYPOINT_TOKEN}" \
            -H "Content-Type: application/json" \
            --data '{"spec":{"groupId":"8ccbc578-b790-45f9-9859-bca06c81adcd","assetId":"mycicddemoapiaprilapril","version":"1.0.0"},"endpoint":{"uri":null,"proxyUri":null,"isCloudHub":true,"muleVersion4OrAbove":true,"type":null,"deploymentType":"CH"},"instanceLabel":null}')
          api_id=$(echo $response | jq -r '.id')
          echo "API created in API Manager with ID ${api_id}"

      - name: Output API ID
        run: |
          echo "::set-output name=api_id::${api_id}"
